/// Flutter icons TestIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  TestIcons
///      fonts:
///       - asset: fonts/TestIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class TestIcons {
  TestIcons._();

  static const _kFontFam = 'TestIcons';
  static const String? _kFontPkg = null;

  static const IconData bicingParking = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bike = IconData(0xe483, fontFamily: 'MaterialIcons', fontPackage: _kFontPkg);
  static const IconData ebike = IconData(0xe223, fontFamily: 'MaterialIcons', fontPackage: _kFontPkg);
  static const IconData eCar = IconData(0xe224, fontFamily: 'MaterialIcons', fontPackage: _kFontPkg);
  static const IconData eCharger = IconData(0xe23d, fontFamily: 'MaterialIcons', fontPackage: _kFontPkg);
  static const IconData speedType = IconData(0xf079c, fontFamily: 'MaterialIcons', fontPackage: _kFontPkg);

}
